# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Complete checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.0'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    - name: Package application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mcautoback
        path: src/dist/windows # or path/to/artifact

    # currently no tests so pytest is commented out (TODO: BE A GOOD PROGRAMMER)
    #- name: Test with pytest
    #  run: |
    #    pytest
