# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src/src

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/windows

    # currently no tests so pytest is commented out (TODO: BE A GOOD PROGRAMMER)
    #- name: Test with pytest
    #  run: |
    #    pytest
